= BIW3-01 Beleg

In diesem Repository wird der Fortschritt meines Belegs getrackt.
Ich übernehme weder Richtigkeit noch korrektheit der hier implementierten Algorithmen.

== Aufbau des Programms

Da ich nicht weiß wie man ordentlich ein Fortran Projekt aufbaut, habe ich willkürlich folgende Konventionen getroffen

Es gibt folgenden Aufbau innerhalb des `root` Verzeichnisses

.Struktur des Repositories
[source]
----
root
|-- src
    |-- subroutines
    |-- util
    |-- main.f90
|-- build
----

Das `src` Verzeichnis beinhaltet alle Quelltextdateien, das `build` Verzeichnis beinhaltet alle Modules und auch die resultierende ausführbare Datei.

== Befehl zum Kompilieren

Es wird angenommen, dass `gfortran` und `gnuplot` auf dem `PATH` erreichbar sind.

.Windows
[source,dos]
----
gfortran src/modules/Kenngroessen.f90 src/steifigkeitsmatrix.f90 src/aufbauSteifigkeit.f90 src/transformation.f90 src/helper.f90 src/matrixfuell.f90 src/main.f90 src/einlese.f90 src/loesungGLS.f90 src/aufbauVektorKnotenlasten.f90 src/aufbauVektorVerschiebungen.f90 src/rueckwartseinsetzen.f90 src/GAUSZ.FOR src/FFREAD.FOR src/rconv.FOR -Jbuild -o build/outa.exe
start outa.exe
----

bzw.

.Unix-like Systeme
[source,dos]
----
gfortran src/main.f90 -o build/out.out
----

== Code Stil

Es werden 2 zentrale Prinzipien in diesem Repository eingehalten:

// DRY:: Dont. Repeat. Yourself
// Jegliche Unterprogramme und oder Funktionen müssen als solche ausgelagert werden. Es werden keine redundanten Algorithmen akzeptiert.

RAII:: Resource Aquisition is Initialization.
Dieses Prinzip ist damit eingehalten, dass jeder Programmabschnitt genau **eine** Verantwortlichkeit, genau **ein** Problem löst.
